### PR TITLE
Fix #45: Enhancement to allow service provider overrides by user

### LINKED ISSUE #45: Facility to override existing service provider
Currently passthrough throws an exception if it finds a duplicate service provider for a given service type. For writing and testing new service providers that may override an existing service provider existing in the class path, it will be really nice if there is a hack in the passthrough that allows an explicitly registered service provider through registerServiceProvider API to override the Service Provider that is found in the class path in some dependent jars (instead of the current behaviour of throwing an error when a duplicate is found).

This will allow testers/developers of the new service provider to not only develop the new service provider. make progress, including raising PRs, while the dependent jars that contains the conflicting service providers are re-packaged.

### PR DESCRIPTION
**Pull request by rkavanap**
This is an enhancement for service developers to test services under development that may override existing services in other jar files.

This change has been tested as well as build successfully on some of the dependent repos, by temporarily bumping up version numbers in these repos (e.g ehcache).

### CODE REVIEW

**Comment by jd0-sag** [comment]
This should be a different API, not implicitly making all explicitly registered services behave this way.  The reason is that the common path should behave more like tc-core and this should really only be something someone opts into due to a packaging scenario they can't easily resolve for a simple test.

**Comment by rkavanap** [comment]
Ok. That make sense. I will add a different API and updated the PR.

The reason I did it this way is because no one must be anyway using this as the assert is in place.
But like you said, it is better if the caller explicitly sets this with a separate call and knows what he or she is getting into.

**Comment by jd0-sag** [comment]
Can you combine these commits into one?  It otherwise looks reasonable.  I just don't want the intermediary discussion points in the version history (since they are steps in implementing the same idea in its first version).

**Comment by rkavanap** [comment]
ok. done now. Wanted you to take a look at the diff before squashing the commits.

**Pull request merged**
